
[project]
name = "qnn-codebase"
version = "0.2.0"
requires-python = ">=3.10"
dependencies = [
  "qiskit>=2.0.0",
  "qiskit-machine-learning>=0.7.0",
  "qiskit-aer>=0.15.1",
  "qiskit-ibm-runtime>=0.27.0",
  "joblib>=1.3.0",
  "matplotlib>=3.7.0",
]

[tool.setuptools]
include-package-data = true
